# This NB demonstrates how we can use plot_ngrams_heatmap

We can use the method to plot all patterns, double click on specific patterns to highlight them in the heatmaps, and select top patterns to plot them on their own.

In [3]:
from intervals.main_rf import *
import pandas as pd
import altair as alt
import visualizations as viz

music21: Certain music21 functions might need the optional package matplotlib;
                  if you run into errors, install it by following the instructions at
                  http://mit.edu/music21/doc/installing/installAdditional.html

In [4]:
root = "https://raw.githubusercontent.com/CRIM-Project/CRIM-online/master/crim/static/mei/MEI_4.0/"
prefix = "CRIM_Model_00"
files = ["08"] 
postfix = ".mei"

## Overall of what `plot_ngrams_heatmap` can do

First, we do the normal steps to get a ngrams dataframe.

In [5]:
corpus = CorpusBase([root + prefix + files[0] + postfix])
model = corpus.scores[0]
mel = model.getMelodic(kind='d', compound=False, unit=0)
mel_ngrams = model.getNgrams(df=mel, n=5, cell_type=str)

Successfully imported.

In [6]:
print(model.getSoundingCount.__doc__)

        This would return a series with the number of parts that currently have
        a note sounding.

In [7]:
model.getMeasure().dropna()

       [Superius]  Altus  Tenor  Bassus
0.0           1.0    1.0    1.0     1.0
8.0           2.0    2.0    2.0     2.0
16.0          3.0    3.0    3.0     3.0
24.0          4.0    4.0    4.0     4.0
32.0          5.0    5.0    5.0     5.0
...           ...    ...    ...     ...
704.0        89.0   89.0   89.0    89.0
712.0        90.0   90.0   90.0    90.0
720.0        91.0   91.0   91.0    91.0
728.0        92.0   92.0   92.0    92.0
736.0        93.0   93.0   93.0    93.0

[93 rows x 4 columns]

In [8]:
model.getBeat().dropna()

        [Superius]  Altus  Tenor  Bassus
0.0            1.0    1.0    1.0     1.0
16.0           1.0    1.0    1.0     1.0
32.0           1.0    1.0    1.0     1.0
48.0           1.0    1.0    1.0     1.0
64.0           1.0    1.0    1.0     1.0
...            ...    ...    ...     ...
1212.0         3.0    3.0    3.0     3.0
1232.0         1.0    1.0    1.0     1.0
1236.0         3.0    3.0    3.0     3.0
1240.0         1.0    1.0    1.0     1.0
1244.0         3.0    3.0    3.0     3.0

[84 rows x 4 columns]

In [9]:
df = model.getNoteRest().dropna()
df

       [Superius] Altus Tenor Bassus
0.0            G4  Rest  Rest   Rest
16.0           D5    G3  Rest   Rest
32.0         Rest    D4    G3   Rest
48.0         Rest  Rest    D4     G2
64.0           A4  Rest  Rest     D3
...           ...   ...   ...    ...
1212.0         F5    A4    B3     G3
1232.0         E5    G4  Rest   Rest
1236.0         E5    G4    C4     C3
1240.0         D5    G4    C4     C4
1244.0         C5    E4    B3     G3

[84 rows x 4 columns]

In [10]:
corpus = CorpusBase(['https://crimproject.org/mei/CRIM_Model_0016.mei'])
model = corpus.scores[0]
nr = model.getNoteRest()
beat = model.getBeat()
# print(beat)
new_nr = model.detailIndex(nr)
new_nr

Successfully imported.

             Discantus Contratenor Tenor Bassus
Measure Beat
1       1.0       Rest          G4  Rest   Rest
2       1.0       Rest          G4  Rest   Rest
        3.0        NaN          F4   NaN    NaN
3       1.0       Rest          G4  Rest     G3
4       1.0       Rest          G4  Rest     G3
...                ...         ...   ...    ...
98      3.0         A4          F4   NaN    NaN
99      1.0         F4         NaN   NaN    NaN
        2.0         G4          C4   NaN    NaN
        3.0        NaN          D4   NaN    NaN
100     1.0         G4          D4   NaN    NaN

[369 rows x 4 columns]

In [11]:
print(new_nr.loc[18, 1.0])

             Discantus Contratenor Tenor Bassus
Measure Beat
18      1.0       None        Rest    A3   Rest

Then we pass the model and the ngram df into the method `plot_ngrams_heatmap`

We could click on the pattern in the top bar chart, and `shift+click` to select more patterns to display in the second chart like [here]("http://g.recordit.co/Le550mfczV.gif")

In [12]:
mel_ngram_chart, mel_ngrams_heatmap_df = viz.plot_ngrams_heatmap(model, mel_ngrams)
mel_ngram_chart

AttributeError: 'ImportedPiece' object has no attribute 'copy'

### Selecting patterns

We could only include some patterns in the heatmaps

First, I collected the top patterns and turned these patterns into a list.

In [29]:
# count and get the 10 most popular patterns
mel_ngrams_top_patterns_df = mel_ngrams.stack().value_counts().to_frame().head(10)
# retrieve a list to generate heatmaps
mel_ngrams_top_patterns_list = mel_ngrams_top_patterns_df.index.to_list()
mel_ngrams_top_patterns_df

                    0
1, 2, -2, -2, -2   13
2, -2, -2, -2, -2  11
1, 1, 2, -2, -2     9
2, -3, 2, -2, -2    8
-3, 2, -2, -2, -2   8
-2, -2, -2, 2, 2    8
-2, -2, -2, -2, 2   7
2, -3, 2, -3, 2     7
2, -3, 2, 2, 2      6
-3, 2, 2, 2, -3     6

In [6]:
mel_ngrams_top_patterns_list

['-3, 2, 2, 2, 2',
 '2, 2, -2, -2, -2',
 '1, 1, -2, -2, -2',
 '1, 1, 3, 1, 2',
 '2, -2, -2, -2, 2',
 '1, -2, -2, -2, 2',
 '-2, -2, 2, 2, 2',
 '2, -3, 2, -2, -2',
 '-3, 2, -2, -2, -2',
 '2, 2, 2, -2, -2']

We would pass the list of patterns into the `patterns` parametter.

In [7]:
chart, mel_ngrams_matches_df = viz.plot_ngrams_heatmap(model, mel_ngrams, patterns=mel_ngrams_top_patterns_list)
chart

alt.VConcatChart(...)

**Cross-checking output from the heatmap with the ngrams dataframe**

We can see that'1, 1, 1, 1, 1' is a really popular pattern. Let's view its start and end points in ngram and in the heatmap's dataframe to make sure that it has been calculated correctly

mel_ngrams[mel_ngrams == '1, 1, 1, 1, 1'].stack().dropna().to_frame()

In [9]:
mel_ngrams_matches_df[mel_ngrams_matches_df['pattern'] == '1, 1, 1, 1, 1']

Empty DataFrame
Columns: [start, end, pattern, voices]
Index: []

## Here plot_ngrams_heatmap is used with ngrams and getHarmonic

Here getHarmonic is used to retrieve patterns, and the top 10 most popular patterns are plotted.

In [37]:
harm = model.getHarmonic(kind="d", compound=True)
h_ng = model.getNgrams(df=harm, how='modules', exclude=['Rest'], cell_type="str")
h_ng

,Altus_[Superius],Tenor_Altus,Tenor_[Superius],Bassus_Tenor,Bassus_Altus,Bassus_[Superius]
16.0,"12_4, 10_Held, 8",NaN,NaN,NaN,NaN,NaN
20.0,"10_Held, 8_1, 8",NaN,NaN,NaN,NaN,NaN
32.0,NaN,"5_4, 3_Held, 1",NaN,NaN,NaN,NaN
36.0,NaN,"3_Held, 1_1, 1",NaN,NaN,NaN,NaN
48.0,NaN,NaN,NaN,"12_4, 10_Held, 8",NaN,NaN
...,...,...,...,...,...,...
1248.0,NaN,"4_Held, 5_2, 4","8_Held, 7_2, 6",NaN,"6_Held, 7_-2, 8","10_Held, 9_-2, 10"
1252.0,NaN,"5_2, 4_Held, 4","7_2, 6_Held, 7",NaN,"7_-2, 8_Held, 8","9_-2, 10_Held, 11"
1256.0,NaN,"4_Held, 4_-2, 5","6_Held, 7_-2, 8",NaN,"8_Held, 8_-5, 12","10_Held, 11_-5, 15"
1268.0,NaN,"4_-2, 5_Held, 5","7_-2, 8_Held, 8",NaN,"8_-5, 12_Held, 12","11_-5, 15_Held, 15"
1272.0,NaN,"5_Held, 5_1, 5","8_Held, 8_1, 8",NaN,"12_Held, 12_1, 12","15_Held, 15_1, 15"

In [15]:
h_ng_top_patterns_df = h_ng.stack().value_counts().to_frame().head(20)
h_ng_chart, h_ng_heat_map_df = viz.plot_ngrams_heatmap(model, h_ng, patterns=h_ng_top_patterns_df.index.to_list())
h_ng_chart

alt.VConcatChart(...)

## Alex new sliding windows feature

In [54]:
varied_size_ngrams = model.getNgrams(df=model.getMelodic(), max_n=5, report=True)
# varied_size_ngrams.stack().value_counts().to_frame().head(25)
a = varied_size_ngrams[0].head(50)
a

,Superius,Contratenor,PrimusTenor,SecundusTenor,Bassus
4.0,"(P5, -M2, M2, m3, -m2)",NaN,NaN,NaN,NaN
10.0,"(-M2, M2, m3, -m2, -M2)",NaN,NaN,NaN,NaN
12.0,"(M2, m3, -m2, -M2, -M2)",NaN,NaN,NaN,NaN
14.0,"(m3, -m2, -M2, -M2, -m3)",NaN,NaN,NaN,NaN
16.0,"(-m2, -M2, -M2, -m3, m2)","(P4, -M2, M2, m3, -m2)",NaN,NaN,NaN
18.0,"(-M2, -M2, -m3, m2, M3)",NaN,NaN,NaN,NaN
21.0,"(-M2, -m3, m2, M3, -M2)",NaN,NaN,NaN,NaN
22.0,"(-m3, m2, M3, -M2, -M2)","(-M2, M2, m3, -m2, -M2)",NaN,NaN,NaN
24.0,"(m2, M3, -M2, -M2, -m2)","(M2, m3, -m2, -M2, -M2)",NaN,NaN,NaN
26.0,"(M3, -M2, -M2, -m2, -M2)","(m3, -m2, -M2, -M2, -m3)",NaN,NaN,NaN
28.0,"(-M2, -M2, -m2, -M2, m3)","(-m2, -M2, -M2, -m3, M2)",NaN,NaN,NaN
30.0,"(-M2, -m2, -M2, m3, -m2)","(-M2, -M2, -m3, M2, m2)",NaN,NaN,NaN
33.0,NaN,"(-M2, -m3, M2, m2, M2)",NaN,NaN,NaN
34.0,"(-m2, -M2, m3, -m2, m2)","(-m3, M2, m2, M2, M2)",NaN,NaN,NaN
35.0,"(-M2, m3, -m2, m2, M2)","(M2, m2, M2, M2, -P5)",NaN,NaN,NaN
36.0,"(m3, -m2, m2, M2, -m3)","(m2, M2, M2, -P5, P4)","(P5, -M2, M2, m3, -m2)",NaN,NaN
37.0,NaN,"(M2, M2, -P5, P4, -M2)",NaN,NaN,NaN
38.0,"(-m2, m2, M2, -m3, -M2)","(M2, -P5, P4, -M2, M2)",NaN,NaN,NaN
40.0,"(m2, M2, -m3, -M2, m3)",NaN,NaN,NaN,NaN
41.0,NaN,"(-P5, P4, -M2, M2, -M2)",NaN,NaN,NaN
42.0,"(M2, -m3, -M2, m3, -m2)","(P4, -M2, M2, -M2, -m3)","(-M2, M2, m3, -m2, -M2)",NaN,NaN
44.0,"(-m3, -M2, m3, -m2, -M2)",NaN,"(M2, m3, -m2, -M2, -M2)",NaN,NaN
46.0,NaN,"(-M2, M2, -M2, -m3, m3)","(m3, -m2, -M2, -M2, -m3)",NaN,NaN
48.0,"(-M2, m3, -m2, -M2, M2)","(M2, -M2, -m3, m3, -m2)","(-m2, -M2, -M2, -m3, m2)",NaN,"(P4, -M2, M2, m3, -m2)"
50.0,NaN,NaN,"(-M2, -M2, -m3, m2, M3)",NaN,NaN
51.0,NaN,"(-M2, -m3, m3, -m2, -M2)",NaN,NaN,NaN
52.0,NaN,"(-m3, m3, -m2, -M2, M2)",NaN,NaN,NaN
53.0,NaN,NaN,"(-M2, -m3, m2, M3, -M2)",NaN,NaN
54.0,NaN,"(m3, -m2, -M2, M2, m2)","(-m3, m2, M3, -M2, M2)",NaN,"(-M2, M2, m3, -m2, -M2)"
56.0,NaN,"(-m2, -M2, M2, m2, -m2)","(m2, M3, -M2, M2, -M2)",NaN,"(M2, m3, -m2, -M2, -M2)"
58.0,NaN,"(-M2, M2, m2, -m2, m2)","(M3, -M2, M2, -M2, -M2)",NaN,"(m3, -m2, -M2, -M2, -m2)"
60.0,NaN,"(M2, m2, -m2, m2, M2)",NaN,NaN,"(-m2, -M2, -M2, -m2, m2)"
62.0,NaN,"(m2, -m2, m2, M2, M2)","(-M2, M2, -M2, -M2, -m2)",NaN,NaN
63.0,NaN,"(-m2, m2, M2, M2, -M2)",NaN,NaN,"(-M2, -M2, -m2, m2, M2)"
64.0,NaN,"(m2, M2, M2, -M2, -M2)","(M2, -M2, -M2, -m2, m2)",NaN,"(-M2, -m2, m2, M2, -m3)"
66.0,NaN,"(M2, M2, -M2, -M2, -m2)","(-M2, -M2, -m2, m2, -m3)",NaN,"(-m2, m2, M2, -m3, -M2)"
67.0,NaN,NaN,"(-M2, -m2, m2, -m3, M2)",NaN,NaN
68.0,NaN,"(M2, -M2, -M2, -m2, m2)",NaN,"(P5, -M2, M2, m3, -m2)","(m2, M2, -m3, -M2, M2)"
70.0,NaN,"(-M2, -M2, -m2, m2, M3)",NaN,NaN,"(M2, -m3, -M2, M2, m2)"
72.0,NaN,NaN,NaN,NaN,"(-m3, -M2, M2, m2, M2)"
74.0,NaN,"(-M2, -m2, m2, M3, P1)",NaN,"(-M2, M2, m3, -m2, -M2)",NaN
75.0,NaN,"(-m2, m2, M3, P1, -M3)",NaN,NaN,NaN
76.0,"(P5, -M2, M2, m3, -m2)","(m2, M3, P1, -M3, M2)",NaN,NaN,"(-M2, M2, m2, M2, M2)"
77.0,NaN,NaN,NaN,NaN,"(M2, m2, M2, M2, m2)"
78.0,NaN,"(M3, P1, -M3, M2, M2)",NaN,NaN,"(m2, M2, M2, m2, M2)"
79.0,NaN,NaN,NaN,NaN,"(M2, M2, m2, M2, -M2)"
80.0,NaN,NaN,NaN,NaN,"(M2, m2, M2, -M2, -m2)"
81.0,NaN,NaN,NaN,NaN,"(m2, M2, -M2, -m2, m2)"
82.0,"(-M2, M2, m3, -m2, -M2)","(P1, -M3, M2, M2, -P5)",NaN,NaN,"(M2, -M2, -m2, m2, M2)"
84.0,"(M2, m3, -m2, -M2, -M2)","(-M3, M2, M2, -P5, P5)",NaN,NaN,NaN

In [61]:
# Combines measure numbers with the df of ngrams
b = model.getMeasure()
c = pd.concat([a, b],axis=1).fillna('-')
c

,Superius,Contratenor,PrimusTenor,SecundusTenor,Bassus,Superius,Contratenor,PrimusTenor,SecundusTenor,Bassus
0.0,-,-,-,-,-,1.0,1.0,1.0,1.0,1.0
4.0,"(P5, -M2, M2, m3, -m2)",-,-,-,-,-,-,-,-,-
8.0,-,-,-,-,-,2.0,2.0,2.0,2.0,2.0
10.0,"(-M2, M2, m3, -m2, -M2)",-,-,-,-,-,-,-,-,-
12.0,"(M2, m3, -m2, -M2, -M2)",-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...
1040.0,-,-,-,-,-,130.0,130.0,130.0,130.0,130.0
1048.0,-,-,-,-,-,131.0,131.0,131.0,131.0,131.0
1056.0,-,-,-,-,-,132.0,132.0,132.0,132.0,132.0
1064.0,-,-,-,-,-,133.0,133.0,133.0,133.0,133.0
1072.0,-,-,-,-,-,134.0,134.0,134.0,134.0,134.0

In [57]:
# Number of voices sounding at any particular offset

model.getSoundingCount()

0.0       1
4.0       1
8.0       1
10.0      1
12.0      2
         ..
1065.0    5
1066.0    5
1068.0    5
1070.0    5
1072.0    5
Name: Sounding, Length: 782, dtype: int64